import type { Metadata } from "next";
export const metadata: Metadata = {
    title: "KiddyGoo | Subscriptions",
    description: "Generated by create love",
};
import { Footer } from "@/components/layouts/footer";

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <main>
                {children}
            </main>
            <Footer />
        </>
    );
}
