import type { Metadata } from "next";
import { Quicksand, Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/lib/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { SupabaseProvider } from "@/providers/SupabaseProvider";
import { Analytics } from "@vercel/analytics/next"


const quicksand = Quicksand({ variable: "--font-quicksand", subsets: ["latin"], display: "swap" });
const inter = Inter({ variable: "--font-inter", subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "KiddyGoo",
  description: "Generated by create love",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${quicksand.variable} ${inter.variable} antialiased font-body`}>
        <SupabaseProvider initialSession={null}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
          <Toaster />
          <Analytics/>
        </SupabaseProvider>
      </body>
    </html>
  );
}
